using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ThirteenthAvenue.Models;

namespace ThirteenthAvenue.Services.Pdf
{
    public class TicketPdfService
    {
        public byte[] GenerateBookingTicketPdf(
            Booking booking,
            Event ev,
            List<BookingItem> bookingItems,
            string customerName,
            string customerEmail)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .Text("13th Avenue Ticket")
                        .SemiBold()
                        .FontSize(22)
                        .FontColor(Colors.Blue.Darken2);

                    page.Content().Column(column =>
                    {
                        column.Spacing(12);

                        column.Item().Border(1).Padding(12).Column(inner =>
                        {
                            inner.Spacing(6);

                            inner.Item().Text($"Booking Reference: {booking.BookingReference}").Bold();
                            inner.Item().Text($"Transaction Reference: {booking.PaymentReference}");
                            inner.Item().Text($"Customer Name: {customerName}");
                            inner.Item().Text($"Customer Email: {customerEmail}");
                        });

                        column.Item().Border(1).Padding(12).Column(inner =>
                        {
                            inner.Spacing(6);

                            inner.Item().Text(ev.Title).Bold().FontSize(18);
                            inner.Item().Text($"Category: {ev.Category?.Name}");
                            inner.Item().Text($"Date: {ev.EventDate:dd MMM yyyy}");
                            inner.Item().Text($"Time: {ev.StartTime:hh\\:mm} - {ev.EndTime:hh\\:mm}");
                            inner.Item().Text($"Venue: {ev.Venue}, {ev.City}");
                        });

                        column.Item().Text("Tickets").Bold().FontSize(16);

                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Element(CellStyle).Text("Ticket Type").Bold();
                                header.Cell().Element(CellStyle).Text("Unit Price").Bold();
                                header.Cell().Element(CellStyle).Text("Qty").Bold();
                                header.Cell().Element(CellStyle).Text("Line Total").Bold();
                            });

                            foreach (var item in bookingItems)
                            {
                                table.Cell().Element(CellStyle).Text(item.TicketType?.Name ?? "");
                                table.Cell().Element(CellStyle).Text($"{item.UnitPrice:N2} RWF");
                                table.Cell().Element(CellStyle).Text(item.Quantity.ToString());
                                table.Cell().Element(CellStyle).Text($"{item.LineTotal:N2} RWF");
                            }

                            static IContainer CellStyle(IContainer container)
                            {
                                return container.Border(1).Padding(6);
                            }
                        });

                        column.Item().AlignRight().Text($"Total Paid: {booking.TotalAmount:N2} RWF").Bold();

                        column.Item().PaddingTop(10).Text("Please present this ticket at the event entrance.");
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by 13th Avenue");
                });
            }).GeneratePdf();
        }
    }
}